spring.datasource.url=jdbc:mysql://nutrivida-db.ceqlr0xedpg5.us-east-1.rds.amazonaws.com:3306/nutrivida?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=admin
spring.datasource.password=Jleon210.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar integración con Azure AD[cite: 3]
spring.cloud.azure.active-directory.enabled=true[cite: 3]

# Client ID de tu API registrada en Entra ID[cite: 3]
spring.cloud.azure.active-directory.credential.client-id=db5f13af-8b1a-4d80-9944-17ea6ff024cf[cite: 3]

# Application ID URI de tu API backend[cite: 3]
spring.cloud.azure.active-directory.app-id-uri=api://clinica-nutrivida-api[cite: 3]

# URL del emisor (Issuer) oficial para validar los tokens JWT de tu Inquilino
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/018a0cc2-29f7-413d-8044-b28bb3362484/v2.0

server.port=5000