spring.datasource.url=jdbc:mysql://nutrivida-mysql:3306/nutrivida_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=nutri_user
spring.datasource.password=nutri_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración del IDaaS para validación de JWT (reemplazar con tu proveedor real luego)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://tu-proveedor-idaas.com/oauth/v2